version: "3.5"
services:
  app:
    build: .
    command: /app/docker-notify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - docker-notify.env
    restart: always
